### ISSUE TITLE
Build fails test

### ISSUE THREAD

**Issue by ecrax** [himanshusharma89/relic_bazaar#20]
Remove the test from workflow file or rewrite test.

**Comment by himanshusharma89** [comment]
@ecrax I fixed it and commented on the test command. You can take up another issue or create one if you want. And if you want to work on GitHub Action, check this: https://github.com/himanshusharma89/flutterx100/issues/17

**Comment by ecrax** [comment]
I sure will, but the build still fails right? 
Do you know why?

**Comment by himanshusharma89** [comment]
@ecrax Yeah, most probably because of the earlier merge, an import is causing the issue. I'll fix that

**Comment by ecrax** [comment]
Ok cool, just wanted to make sure it is not because of the workflow :)

**Comment by himanshusharma89** [comment]
@ecrax your workflow is good
